CHECKER_FAILED = 0
RUNNER_FAILED = 1
BALANCE_TRANSFER_FAILED = 2
EXECUTE_CMD_FAILED = 3
EXECUTE_CMD_TIMEOUT = 4 
NO_GAS_REMAINING_FOUND = 5 
NO_ACCEPTED_FOUND = 6
CALL_CONTRACT_FAILED = 7
CREATE_CONTRACT_FAILED = 8
JSON_OUTPUT_CORRUPTED = 9
CONTRACT_NOT_EXIST = 10
STATE_CORRUPTED = 11
LOG_ENTRY_INSTALL_FAILED = 12
MESSAGE_CORRUPTED = 13
RECEIPT_IS_NULL = 14
MAX_DEPTH_REACHED = 15
CHAIN_CALL_DIFF_SHARD = 16
PREPARATION_FAILED = 17
NO_OUTPUT = 18
OUTPUT_ILLEGAL = 19
MAP_DEPTH_MISSING = 20